server:
  #服务端口
  port: 9010

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: server-01-route
          uri: lb://SERVER-01
          predicates:
            - Path=/server-01/**
          # 前缀过滤，默认配置下，我们的请求路径是 http://localhost:9010/service-01/** 这时会路由到指定的服务
          # 此处配置去掉1个路径前缀，再配置上面的 Path=/server-01/**，就能按照 http://localhost:9000/server-01/** 的方式访问了
          filters:
            - StripPrefix=1

        - id: ribbon-consumer-route
          uri: lb://ribbon-consumer
          predicates:
          - Path=/ribbon-consumer/**

eureka:
  instance:
    #eureka主机名，会在控制页面中显示
    hostname: localhost
    prefer-ip-address: true
    #eureka服务器页面中status的请求路径
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8001/eureka/



